version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:latest

  tests:
    build: .
    command: pytest app/test_main.py
    depends_on:
      - web
    env_file: .env
